spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Timezone: MST
    url: jdbc:mysql://localhost:3306/mealwrap?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=America/Edmonton&useLegacyDatetimeCode=false
    username: root
    password: 123456
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always
  application:
    name: Mealwrap
  redis:
    timeout: 60000
    database: 0
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml